name: Workflows with secrets

on: push

env:
    API_KEY: ${{ secrets.API_KEY }}

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
        - name: read secret
          run: echo "key id ${{ secrets.API_KEY }}"
        - name: read secret
          run: echo "variable id ${{ env.API_KEY }}"
